# A sample Gemfile
source "https://rubygems.org"
ruby '2.2.4'

# gem "rails"

# Assets
gem 'sinatra'
gem 'therubyracer'
gem 'haml'
gem 'sass'
gem 'coffee-script'
gem 'google-api-client', '0.9'

group :development do
  gem 'foreman'
end
